version: 2
updates:
  # Keep GitHub Actions versions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  # Keep MkDocs and plugin versions up to date
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      mkdocs:
        patterns:
          - "*"
